#!/usr/bin/env bash
target=$1
backup_target=$2


if [[ ! $target ]] || [[ ! $backup_target ]] || [[ ! -e "$target" ]] || [[ ! -e "$backup_target" ]]; then
  echo "Usage: test [user@host:]/target /backup_target"
  exit 1
fi

next_backup=$(date +'%Y-%m-%d_%H-%M-%S') # generate next backup

if [[ -z "$(ls $backup_target)" ]]; then
    # make the first backup if backup_target directory is empty
    echo "making first backup (${target}) -> (${next_backup})"
    rsync -azvh "${target}/" "${backup_target}/${next_backup}"
else
    # otherwise make an incremental backup
    last_backup=$(ls -t "${backup_target}/" | head -n 1) # get last_backup from timestamp
    echo "making incremental backup (${target}) -> (${last_backup} -> ${next_backup})"
    rsync -azvh --hard-links --link-dest="../${last_backup}" "${target}/" "${backup_target}/${next_backup}" # copy to next_backup, make hard links from last_backup if necessary
fi
