#!/usr/bin/env bash
target=$1
backup_target=$2


if [[ ! $target ]] || [[ ! $backup_target ]] || [[ ! -e "$target" ]]; then
  echo "Usage: test [user@host:]/target /backup_target"
  exit 1
fi
next_backup=$(date +'%Y-%m-%d_%H-%M-%S')

if [[ ! -d $backup_target ]] || [[ -z "$(ls $backup_target)" ]]; then
    echo "making first backup (${target}) -> (${next_backup})"
    mkdir -p $backup_target
    rsync -azvh $target "${backup_target}/${next_backup}"
else
    # make incremental backup
    last_backup=$(ls -t "${backup_target}/" | head -n 1)
    echo "making incremental backup (${target}) -> (${last_backup} -> ${next_backup})"
    rsync -azvh --hard-links --link-dest="./${last_backup}" $target "${backup_target}/${next_backup}"

fi